### ISSUE TITLE
Grf does not open

### ISSUE THREAD

**Issue by JhonLSV** [xBrunoMedeiros/RODumper#1]
The Grf on this server has another type of protection, so it is not being opened completely
https://drive.google.com/file/d/1FykJlPtoisyUxBiT4n-ZO2bL5Sbryh-f/view

**Comment by xBrunoMedeiros** [comment]
Use this commit and inject with any injector, I have used "SystemInformer" it works perfectly.
https://github.com/xBrunoMedeiros/RODumper/commit/d7e702f51e6d187c97c655cf5e9ec56b382cce36

**Comment by dantoki** [comment]
i use systemInformer but the client doesnt open since its finding a gepard
